name: Github Pages

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn run build
        env: 
          CI: false
      - name: Deploy
        run: |
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      # - uses: JamesIves/github-pages-deploy-action@3.6.1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: dist/build
      #     CLEAN: true